message(STATUS "Activating osxcross Cross-Compiler: macOS x86_64")

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if (NOT DEFINED ENV{OSXCROSS_ROOT})
    message(FATAL_ERROR "OSXCROSS_ROOT is not set. Run scripts/prep-macos-osxcross.sh first.")
endif ()

if (NOT DEFINED ENV{OSXCROSS_TARGET})
    message(FATAL_ERROR "OSXCROSS_TARGET is not set. Run scripts/prep-macos-osxcross.sh first.")
endif ()

set(OSXCROSS_ROOT "$ENV{OSXCROSS_ROOT}")
set(OSXCROSS_TARGET "$ENV{OSXCROSS_TARGET}")

if (DEFINED ENV{OSXCROSS_DEPLOYMENT_TARGET})
    set(CMAKE_OSX_DEPLOYMENT_TARGET "$ENV{OSXCROSS_DEPLOYMENT_TARGET}" CACHE STRING "")
else ()
    set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15" CACHE STRING "")
endif ()

set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "")

if (DEFINED ENV{OSXCROSS_CLANG} AND DEFINED ENV{OSXCROSS_CLANGXX})
    set(CMAKE_C_COMPILER "$ENV{OSXCROSS_CLANG}")
    set(CMAKE_CXX_COMPILER "$ENV{OSXCROSS_CLANGXX}")
else ()
    set(CMAKE_C_COMPILER "${OSXCROSS_ROOT}/target/bin/${OSXCROSS_TARGET}-clang")
    set(CMAKE_CXX_COMPILER "${OSXCROSS_ROOT}/target/bin/${OSXCROSS_TARGET}-clang++")
endif ()
set(CMAKE_AR "${OSXCROSS_ROOT}/target/bin/${OSXCROSS_TARGET}-ar")
set(CMAKE_RANLIB "${OSXCROSS_ROOT}/target/bin/${OSXCROSS_TARGET}-ranlib")
set(CMAKE_STRIP "${OSXCROSS_ROOT}/target/bin/${OSXCROSS_TARGET}-strip")

if (DEFINED ENV{OSXCROSS_SDK})
    set(CMAKE_OSX_SYSROOT "$ENV{OSXCROSS_SDK}" CACHE PATH "")
endif ()

if (DEFINED ENV{CROSS_PREFIX})
    set(CROSS_PREFIX "$ENV{CROSS_PREFIX}")
else ()
    set(CROSS_PREFIX "$ENV{HOME}/toolchain/macos/prefix-x86_64")
endif ()

set(CMAKE_FIND_ROOT_PATH
    "${CMAKE_OSX_SYSROOT}"
    "${CROSS_PREFIX}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
